# Generated by Django 3.2.3 on 2022-05-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('contenido', models.PositiveSmallIntegerField()),
                ('gramaje', models.PositiveSmallIntegerField()),
                ('precio', models.PositiveSmallIntegerField()),
                ('cantidad', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
    ]
