# Generated by Django 4.0.4 on 2022-05-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('prescripcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('paciente', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.PositiveSmallIntegerField()),
                ('fecha_entrega', models.DateField()),
                ('fecha_expira', models.DateField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medico')),
            ],
        ),
        migrations.CreateModel(
            name='ListaMedicamentos',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento')),
                ('prescripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.prescripcion')),
            ],
        ),
    ]
