# Generated by Django 4.0.4 on 2022-05-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_prescripcion_comprimidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescripcion',
            name='comprimidos',
        ),
        migrations.RemoveField(
            model_name='prescripcion',
            name='dias_tratamiento',
        ),
        migrations.RemoveField(
            model_name='prescripcion',
            name='frecuencia_hrs',
        ),
        migrations.AddField(
            model_name='listamedicamentos',
            name='comprimidos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listamedicamentos',
            name='dias_tratamiento',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listamedicamentos',
            name='frecuencia_hrs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
