# Generated by Django 4.0.4 on 2022-05-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_prescripcion_comprimidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescripcion',
            name='medicamento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento'),
        ),
    ]
