# Generated by Django 4.0.4 on 2022-05-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_alter_prescripcion_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescripcion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento'),
        ),
    ]
